import turtle

sandbox = turtle.Screen()

geoffrey = turtle.Turtle() 

geoffrey.shape("turtle")

geoffrey.color("tomato")

#name.forward(distance)


#name.right(degrees)
#name.left(degrees)

sideLength = input("How big do you want the shapes to be?")
length = int(sideLength)

geoffrey.begin_fill()
geoffrey.left(90)
geoffrey.forward(length)
geoffrey.left(90)
geoffrey.forward(length)
geoffrey.left(90)
geoffrey.forward(length)
geoffrey.left(90)
geoffrey.forward(length)
geoffrey.left(90)
geoffrey.forward(length)


geoffrey.left(90)
geoffrey.forward(50)
geoffrey.left(90)
geoffrey.forward(50)
geoffrey.left(90)
geoffrey.forward(50)
geoffrey.left(90)
geoffrey.forward(50)
geoffrey.left(90)
geoffrey.forward(100)
geoffrey.right(90)
geoffrey.forward(50)
geoffrey.right(90)
geoffrey.forward(50)
geoffrey.right(90)
geoffrey.forward(100)
geoffrey.color("blue")
geoffrey.forward(50)
geoffrey.left(90)
geoffrey.forward(100)
geoffrey.left(90)
geoffrey.forward(100)
geoffrey.left(90)
geoffrey.forward(50)
geoffrey.color("tomato")
geoffrey.forward(50)
geoffrey.right(90)
geoffrey.forward(50)
geoffrey.color("blue")
geoffrey.forward(50)
geoffrey.left(90)
geoffrey.forward(100)
geoffrey.left(90)
geoffrey.forward(100)
geoffrey.left(90)
geoffrey.forward(50)
geoffrey.color("tomato")
geoffrey.forward(50)
geoffrey.right(120)
geoffrey.forward(200)
geoffrey.right(120)
geoffrey.forward(50)
geoffrey.left(120)
geoffrey.forward(50)
geoffrey.left(120)
geoffrey.forward(50)
geoffrey.forward(400)
geoffrey.left(135)
geoffrey.forward(100)
geoffrey.right(135)
geoffrey.forward(100)
geoffrey.right(145)
geoffrey.forward(100)
geoffrey.right(135)
geoffrey.forward(100)
geoffrey.right(145)
geoffrey.forward(100)

geoffrey.right(90)
geoffrey.penup()
geoffrey.forward(50)
geoffrey.pendown()
geoffrey.left(90)
geoffrey.circle(50)
geoffrey.end_fill()


